### PR TITLE
Rename chssl_checksum_url to cfssl_checksum_url

### PR DESCRIPTION
**Pull request by dsix-work**
I'm assuming that this wasn't made `chssl` intentionally

### CODE REVIEW

**Review by githubixx — COMMENTED** [review]
Oha... Yes, that's of course not correct :wink: Can you adjust it in CHANGELOG.md too? Then we have all the needed changes in one PR. Thx!

**Comment by dsix-work** [comment]
Sure! Should this be a major version bump since a variable name is changing?

**Comment by githubixx** [comment]
Hmm... Well, small change, big impact :wink: ... But yeah, I think it should be a major version bump. Doesn't help.

**Review by githubixx — APPROVED** [review]

**Comment by githubixx** [comment]
Thx for the fix @dsix-work !

**Pull request merged**
